//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public int id_user { get; set; }
        public int id_item { get; set; }
        public int status { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
