//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_user { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
