//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id_item { get; set; }
        public string i_name { get; set; }
        public int price { get; set; }
        public int id_category { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
