//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Carts_Items = new HashSet<Carts_Items>();
        }
    
        public long cartID { get; set; }
        public long userID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Carts_Items> Carts_Items { get; set; }
    }
}
